CREATE TABLE IF NOT EXISTS Users (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Username TEXT UNIQUE NOT NULL,
  PasswordHash BLOB NOT NULL,
  PasswordSalt BLOB NOT NULL,
  Role TEXT NOT NULL,
  FullName TEXT,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Products (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Code TEXT UNIQUE,
  Name TEXT NOT NULL,
  Price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS Stock (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ProductId INTEGER NOT NULL,
  Quantity INTEGER NOT NULL,
  Location TEXT,
  FOREIGN KEY(ProductId) REFERENCES Products(Id)
);

CREATE TABLE IF NOT EXISTS Tables (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Number INTEGER UNIQUE NOT NULL,
  Seats INTEGER
);

CREATE TABLE IF NOT EXISTS Reservations (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  TableId INTEGER NOT NULL,
  CustomerName TEXT,
  Date TEXT NOT NULL,
  TimeSlot TEXT NOT NULL,
  CreatedByUserId INTEGER,
  FOREIGN KEY(TableId) REFERENCES Tables(Id),
  FOREIGN KEY(CreatedByUserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS Orders (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  TableId INTEGER,
  UserId INTEGER,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  Total REAL DEFAULT 0,
  Paid INTEGER DEFAULT 0,
  FOREIGN KEY(TableId) REFERENCES Tables(Id),
  FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS OrderItems (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  OrderId INTEGER NOT NULL,
  ProductId INTEGER,
  Quantity INTEGER,
  UnitPrice REAL,
  FOREIGN KEY(OrderId) REFERENCES Orders(Id),
  FOREIGN KEY(ProductId) REFERENCES Products(Id)
);
